# Generated by Django 2.2 on 2019-04-11 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_thread_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Item'),
        ),
    ]
