# Generated by Django 2.2 on 2019-04-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_offermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermessage',
            name='offerAccept',
            field=models.BooleanField(null=True),
        ),
    ]
