# Generated by Django 2.1.7 on 2019-04-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_offermessage_offeraccept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offermessage',
            name='offer',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10000, null=True),
        ),
    ]
