# Generated by Django 2.1.7 on 2019-04-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20190413_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermessage',
            name='offerDelete',
            field=models.BooleanField(null=True),
        ),
    ]
