# Generated by Django 2.1.7 on 2019-03-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('userID', models.BigIntegerField()),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
