# Generated by Django 2.1.7 on 2019-03-22 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='createdDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
