# Generated by Django 2.1.7 on 2019-04-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20190403_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='displayPhoto',
            field=models.ImageField(null=True, upload_to='item_pics'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10000),
        ),
    ]
