# Generated by Django 2.1.7 on 2019-04-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20190411_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isSoldOut',
            field=models.BooleanField(default=False),
        ),
    ]
